// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 기본값은 서울 리전 자체 Supabase 프로젝트 (anon 키는 RLS로 보호되는 공개 키)
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://syxodrmnukybnnlgttuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eG9kcm1udWt5Ym5ubGd0dHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MjEwOTMsImV4cCI6MjEwMzE5NzA5M30.e96it7mNmSxnC4ygoeB33WGHBUEn4wwjDV5V_1T_rZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// storage 옵션은 지정하지 않는다. persistSession: true 이므로 supabase-js가
// 브라우저에서 globalThis.localStorage를 그대로 쓴다 — 기존에 쓰던 커스텀
// storage도 Lovable 미리보기 호스트가 아니면 localStorage를 그대로 반환했으므로
// 저장 위치·키(sb-<ref>-auth-token)가 동일해 기존 로그인 세션이 유지된다.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
